window.isHackyUserScript = true;

function OPTIONS_HTML() {
var html="";
html += "<style>";
html += "	#kyberia_v31				{ padding: 10px 20px; max-width: 400px; margin: 0 auto; }";
html += "	#kyberia_v31 input			{ color: white; background: #000; border: 1px solid #6dae42;";
html += "									padding: 2px 4px; font-family: monospace; font-size: 9pt; }";
html += "	#kyberia_v31 .infotext		{ color: #555; text-align: center; margin-bottom: 0; }";
html += "";
html += "	#kyberia_v31 section		{ margin-left: 10px; clear: both; padding: 5px 0; }";
html += "	#kyberia_v31 section>div	{ margin-left: 110px; margin-top: 10px; }";
html += "	#kyberia_v31 input[type=\"checkbox\"] { cursor: pointer; height: 12px; }";
html += "	#kyberia_v31 input			{ margin-right: 10px; }";
html += "	#kyberia_v31 input.wide		{ width: 90%; }";
html += "	#kyberia_v31 h2				{ float: left; width: 100px; color: #555; }";
html += "	#kyberia_v31 div			{ display: block; margin-bottom: 1px; }";
html += "	#kyberia_v31 .disabled		{ opacity: 0.3; pointer-events: none; }";
html += "	#kyberia_v31 div p			{ margin-left: 30px; color: #555; margin-top: 0px; margin-bottom: 2px; }";
html += "	#kyberia_v31 .ls.nah		{ background: red; }";
html += "	#kyberia_v31 .saved 		{ display: none; float: right; color: red; font-weight: bold; }";
html += "";
html += "<\/style>";
html += "";
html += "<div id=\"kyberia_v31\">";
html += "";
html += "	<h1>Kyberia v3.1 features &nbsp; <a href=\"http:\/\/kyberia.sk\/id\/63603\" style=\"font-size: 20px;\">+ suggest<\/a><\/h1>";
html += "	<hr>";
html += "	<b class=\"saved\">SAVED!<\/b>";
html += "	<p class=\"infotext\">changes are automatically saved<\/p>";
html += "";
html += "	<section>";
html += "		<h2>Users<\/h2>";
html += "		<div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"StopAvatars\" class=\"ls\"> stop avatar animation<\/label>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"HideAvatars\" class=\"ls\"> hide avatars<\/label>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"Desocializer\" class=\"ls\"> desocializer - hide avatars &amp; names<\/label>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"TagUsers\" class=\"ls\"> tag users<\/label>";
html += "				<p>";
html += "					<input type=\"text\" name=\"TagUsers\" class=\"ls wide\"><br>";
html += "					773:memfer -&gt; changed_name<sup>memfer<\/sup><br>";
html += "					separate with spaces: \"1:name 2:name 3:name\"";
html += "				<\/p>";
html += "			<\/div>";
html += "";
html += "		<\/div>";
html += "	<\/section>";
html += "";
html += "	<section>";
html += "		<h2>Nodes<\/h2>";
html += "		<div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"HideMoods\" class=\"ls\"> hide mood messages<\/label>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"LimitNodeHeight\" class=\"ls\"> limit node height<\/label>";
html += "				<p>adds 'show more' button to long posts<\/p>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"CompactMode\" class=\"ls\"> compact mode<\/label>";
html += "				<p>see how it looks <a href=\"#\">here<\/a><\/p>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"InplaceEditing\" class=\"ls\"> inplace editing<\/label>";
html += "				<p>Re[23]: node name title | conf | edit<\/p>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"QuickReply\" class=\"ls\"> quick reply<\/label>";
html += "				<p>adds 'reply' button for quick reply<\/p>";
html += "			<\/div>";
html += "		<\/div>";
html += "	<\/section>";
html += "";
html += "	<section>";
html += "		<h2>UI fix<\/h2>";
html += "		<div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"AjaxButtons\" class=\"ls\"> K, FOOK, BOOK without refresh<\/label>";
html += "				<p>+ FOOKs in background, and hides the node<\/p>";
html += "				<p>+ BOOKs in background<\/p>";
html += "				<p>+ K! in background, K! button in every node<\/p>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"DeleteButton\" class=\"ls\"> DELETE to recycle node to 123456<\/label>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"KeyShortcuts\" class=\"ls\"> keyboard shortcuts<\/label>";
html += "				<p>B\/N - previous\/next submission<\/p>";
html += "			<\/div>";
html += "		<\/div>";
html += "	<\/section>";
html += "";
html += "	<section>";
html += "		<h2>Misc<\/h2>";
html += "		<div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"MailUpgrade\" class=\"ls\"> mail upgrade<\/label>";
html += "					(<a href=\"http:\/\/kyberia.sk\/id\/6505157\">about<\/a>)";
html += "				<p>+ show last mailed users, click to filter<\/p>";
html += "				<p>+ online status<\/p>";
html += "			<\/div>";
html += "			<div>";
html += "				<label><input type=\"checkbox\" name=\"DoplnacDiakritiky\" class=\"ls\"> dopĺňač diakritiky<\/label>";
html += "					(<a href=\"http:\/\/kyberia.sk\/id\/7134215\">about<\/a>)";
html += "			<\/div>";
html += "			<!-- <div><input type=\"checkbox\" name=\"Facebookizer\" class=\"ls\">";
html += "				 <a href=\"http:\/\/kyberia.sk\/id\/6771353\">facebookizer<\/a><\/div>";
html += "			-->";
html += "		<\/div>";
html += "	<\/section>";
html += "";
html += "	<br>";
html += "";
html += "	<hr>";
html += "<\/div>";
return html;
}